### ISSUE TITLE
Modify footer in Homepage

### ISSUE THREAD

**Issue by melvincwng** [Your-First-Open-Source-Project/Community-Website#20]
Problem: i) Wrong href value in the anchor tag of the footer & ii) To modify existing text in the anchor tag of the footer

Solution: i) Change the href to "https://hacktoberfest.com/" and ii) change text to "Created by the community for Hacktoberfest 2022 with ❤️" 

Expectation: The footer should show the correct text & when clicked, it directs user in a new tab to the Hacktoberfest 2022 website.

Note: This is a simple & good first issue for newcomers wanting to contribute to open source or for Hacktoberfest 2022. Preferably looking for someone who **has not** contributed to this repository before. Kindly tag/ping me if you wish to be assigned this task. 

Take care, have fun & good luck 🎉

**Comment by melvincwng** [comment]
@theadityaagnihotri Hi Aditya, sure!

Have assigned it to you :)

**Comment by PanikaGupta** [comment]
hey! 
please assign this to me.

**Comment by melvincwng** [comment]
@PanikaGupta, this issue already has been assigned.

Please stay tuned for other issues in the future 😊

**Comment by melvincwng** [comment]
Closed #21
