### ISSUE TITLE
Add CONTRIBUTORS.md documentation

### ISSUE THREAD

**Issue by melvincwng** [Your-First-Open-Source-Project/Community-Website#7]
To setup a basic CONTRIBUTORS.md markdown file to document the various contributors of this project

**Comment by rahulssv** [comment]
Please assign me!

**Comment by melvincwng** [comment]
@rahulssv Hi Rahul, I will be handling this issue as I require the contributors.md file to be in a specific format.

**Comment by melvincwng** [comment]
Issue is closed from PR #13
